# Generated by Django 6.0.3 on 2026-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
